### ISSUE TITLE
Atom 1.13 Shadow DOM removal

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-dark-atom-syntax#14]
> 🔀 Pull Request: #15

Starting from Atom version 1.13, the contents of `atom-text-editor` [elements are no longer encapsulated within a shadow DOM boundary](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html).
This means the `:host` and `::shadow` pseudo-selectors should be completely removed and all syntax selectors should be prepended with `syntax--`.
To prevent breakage with existing style sheets, Atom will automatically upgrade selectors for versions less or equal to 1.12.

The flight manual provides the great migration guide "[Removing Shadow DOM styles](http://flight-manual.atom.io/shadow-dom/sections/removing-shadow-dom-styles)" for package authors to prepare their packages for this breaking change. 

There are also reference pull requests for the Atom Core theme packages [One Dark Syntax](https://github.com/atom/one-dark-syntax/pull/79) and [One Dark UI](https://github.com/atom/one-dark-ui/pull/168).

**Tasks**
  - [x] Remove all `:host` and `::shadow` pseudo-selectors
  - [x] Prepend all syntax selectors with `syntax--`
  - [x] Add a badhe (shield) for the latest compatible Atom version
  - [x] Update `package.json` minimal Atom engine version to `>=1.13.0`
